### ISSUE TITLE
About epub book format

### ISSUE THREAD

**Issue by honemik** [drkamarul/multivar_data_analysis#3]
Hi! This is the most complete and concise book about how to use R in epidemiology. Thank you for writing this book, it save my time try and error lots of things.
However, I'm trying to port the original book into epub format. I came up with a weird error. I don't know which packages I didn't install. 
in 08_logistic_02,I think it should only loaded with these library:haven, tidyverse, gtsummary, broom, LogisticDx,and here. Is there something I misunderstood?or Is there something I need to install as well?

![圖片](https://user-images.githubusercontent.com/22560792/159895968-55060329-bcfe-4b14-aebb-c6d8288b2ae1.png)

**Comment by drkamarul** [comment]
Thank you for your kind words. Let us check on our side.

**Comment by drkamarul** [comment]
I have checked and I can confirm on my end, I could publish the book into epub format. My suggestion is for you to zip the repo, download it and then re-publish the book on your machine by clicking the **Build** and then **Build Book**  

![image](https://user-images.githubusercontent.com/6749223/160320390-c57979a3-52d5-47b7-a90a-6b8342e9501a.png)
